/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {5, 5, 1};
static const casadi_int casadi_s2[3] = {5, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {1055, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};
static const casadi_int casadi_s6[3] = {28, 1, 1};

/* Solver_expl_ode_hess:(i0[5],i1[5x5],i2[5x2],i3[5],i4[2],i5[1055])->(o0[7],o1[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][3] : 0;
  a04=arg[3]? arg[3][1] : 0;
  a05=(a03*a04);
  a06=(a02*a05);
  a01=sin(a01);
  a07=arg[3]? arg[3][0] : 0;
  a03=(a03*a07);
  a08=(a01*a03);
  a06=(a06-a08);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[3]? arg[3][4] : 0;
  a08=(a01*a04);
  a06=(a06+a08);
  a08=(a02*a07);
  a06=(a06+a08);
  if (res[0]!=0) res[0][3]=a06;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a06=arg[1]? arg[1][3] : 0;
  a08=(a04*a06);
  a08=(a02*a08);
  a09=(a01*a00);
  a10=(a05*a09);
  a08=(a08-a10);
  a10=(a02*a00);
  a11=(a03*a10);
  a12=(a07*a06);
  a12=(a01*a12);
  a11=(a11+a12);
  a08=(a08-a11);
  a00=(a00*a08);
  a10=(a04*a10);
  a09=(a07*a09);
  a10=(a10-a09);
  a06=(a06*a10);
  a00=(a00+a06);
  if (res[1]!=0) res[1][0]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a06=(a00*a08);
  a09=arg[1]? arg[1][8] : 0;
  a11=(a09*a10);
  a06=(a06+a11);
  if (res[1]!=0) res[1][1]=a06;
  a06=arg[1]? arg[1][12] : 0;
  a11=(a06*a08);
  a12=arg[1]? arg[1][13] : 0;
  a13=(a12*a10);
  a11=(a11+a13);
  if (res[1]!=0) res[1][2]=a11;
  a11=arg[1]? arg[1][17] : 0;
  a13=(a11*a08);
  a14=arg[1]? arg[1][18] : 0;
  a15=(a14*a10);
  a13=(a13+a15);
  if (res[1]!=0) res[1][3]=a13;
  a13=arg[1]? arg[1][22] : 0;
  a15=(a13*a08);
  a16=arg[1]? arg[1][23] : 0;
  a17=(a16*a10);
  a15=(a15+a17);
  if (res[1]!=0) res[1][4]=a15;
  a15=arg[2]? arg[2][2] : 0;
  a17=(a15*a08);
  a18=arg[2]? arg[2][3] : 0;
  a19=(a18*a10);
  a17=(a17+a19);
  if (res[1]!=0) res[1][5]=a17;
  a17=arg[2]? arg[2][7] : 0;
  a08=(a17*a08);
  a19=arg[2]? arg[2][8] : 0;
  a10=(a19*a10);
  a08=(a08+a10);
  if (res[1]!=0) res[1][6]=a08;
  a08=(a04*a09);
  a08=(a02*a08);
  a10=(a01*a00);
  a20=(a05*a10);
  a08=(a08-a20);
  a20=(a02*a00);
  a21=(a03*a20);
  a22=(a07*a09);
  a22=(a01*a22);
  a21=(a21+a22);
  a08=(a08-a21);
  a00=(a00*a08);
  a20=(a04*a20);
  a10=(a07*a10);
  a20=(a20-a10);
  a09=(a09*a20);
  a00=(a00+a09);
  if (res[1]!=0) res[1][7]=a00;
  a00=(a06*a08);
  a09=(a12*a20);
  a00=(a00+a09);
  if (res[1]!=0) res[1][8]=a00;
  a00=(a11*a08);
  a09=(a14*a20);
  a00=(a00+a09);
  if (res[1]!=0) res[1][9]=a00;
  a00=(a13*a08);
  a09=(a16*a20);
  a00=(a00+a09);
  if (res[1]!=0) res[1][10]=a00;
  a00=(a15*a08);
  a09=(a18*a20);
  a00=(a00+a09);
  if (res[1]!=0) res[1][11]=a00;
  a08=(a17*a08);
  a20=(a19*a20);
  a08=(a08+a20);
  if (res[1]!=0) res[1][12]=a08;
  a08=(a04*a12);
  a08=(a02*a08);
  a20=(a01*a06);
  a00=(a05*a20);
  a08=(a08-a00);
  a00=(a02*a06);
  a09=(a03*a00);
  a10=(a07*a12);
  a10=(a01*a10);
  a09=(a09+a10);
  a08=(a08-a09);
  a06=(a06*a08);
  a00=(a04*a00);
  a20=(a07*a20);
  a00=(a00-a20);
  a12=(a12*a00);
  a06=(a06+a12);
  if (res[1]!=0) res[1][13]=a06;
  a06=(a11*a08);
  a12=(a14*a00);
  a06=(a06+a12);
  if (res[1]!=0) res[1][14]=a06;
  a06=(a13*a08);
  a12=(a16*a00);
  a06=(a06+a12);
  if (res[1]!=0) res[1][15]=a06;
  a06=(a15*a08);
  a12=(a18*a00);
  a06=(a06+a12);
  if (res[1]!=0) res[1][16]=a06;
  a08=(a17*a08);
  a00=(a19*a00);
  a08=(a08+a00);
  if (res[1]!=0) res[1][17]=a08;
  a08=(a04*a14);
  a08=(a02*a08);
  a00=(a01*a11);
  a06=(a05*a00);
  a08=(a08-a06);
  a06=(a02*a11);
  a12=(a03*a06);
  a20=(a07*a14);
  a20=(a01*a20);
  a12=(a12+a20);
  a08=(a08-a12);
  a11=(a11*a08);
  a06=(a04*a06);
  a00=(a07*a00);
  a06=(a06-a00);
  a14=(a14*a06);
  a11=(a11+a14);
  if (res[1]!=0) res[1][18]=a11;
  a11=(a13*a08);
  a14=(a16*a06);
  a11=(a11+a14);
  if (res[1]!=0) res[1][19]=a11;
  a11=(a15*a08);
  a14=(a18*a06);
  a11=(a11+a14);
  if (res[1]!=0) res[1][20]=a11;
  a08=(a17*a08);
  a06=(a19*a06);
  a08=(a08+a06);
  if (res[1]!=0) res[1][21]=a08;
  a08=(a04*a16);
  a08=(a02*a08);
  a06=(a01*a13);
  a11=(a05*a06);
  a08=(a08-a11);
  a11=(a02*a13);
  a14=(a03*a11);
  a00=(a07*a16);
  a00=(a01*a00);
  a14=(a14+a00);
  a08=(a08-a14);
  a13=(a13*a08);
  a11=(a04*a11);
  a06=(a07*a06);
  a11=(a11-a06);
  a16=(a16*a11);
  a13=(a13+a16);
  if (res[1]!=0) res[1][22]=a13;
  a13=(a15*a08);
  a16=(a18*a11);
  a13=(a13+a16);
  if (res[1]!=0) res[1][23]=a13;
  a08=(a17*a08);
  a11=(a19*a11);
  a08=(a08+a11);
  if (res[1]!=0) res[1][24]=a08;
  a08=(a04*a18);
  a08=(a02*a08);
  a11=(a01*a15);
  a13=(a05*a11);
  a08=(a08-a13);
  a13=(a02*a15);
  a16=(a03*a13);
  a06=(a07*a18);
  a06=(a01*a06);
  a16=(a16+a06);
  a08=(a08-a16);
  a15=(a15*a08);
  a13=(a04*a13);
  a11=(a07*a11);
  a13=(a13-a11);
  a18=(a18*a13);
  a15=(a15+a18);
  if (res[1]!=0) res[1][25]=a15;
  a08=(a17*a08);
  a13=(a19*a13);
  a08=(a08+a13);
  if (res[1]!=0) res[1][26]=a08;
  a08=(a04*a19);
  a08=(a02*a08);
  a13=(a01*a17);
  a05=(a05*a13);
  a08=(a08-a05);
  a02=(a02*a17);
  a03=(a03*a02);
  a05=(a07*a19);
  a01=(a01*a05);
  a03=(a03+a01);
  a08=(a08-a03);
  a17=(a17*a08);
  a04=(a04*a02);
  a07=(a07*a13);
  a04=(a04-a07);
  a19=(a19*a04);
  a17=(a17+a19);
  if (res[1]!=0) res[1][27]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Solver_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
