/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1055, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* Solver_cost_ext_cost_fun:(i0[5],i1[2],i2[],i3[1055])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51;
  a00=arg[3]? arg[3][0] : 0;
  a01=arg[1]? arg[1][0] : 0;
  a01=casadi_sq(a01);
  a00=(a00*a01);
  a01=arg[3]? arg[3][1] : 0;
  a02=arg[1]? arg[1][1] : 0;
  a02=casadi_sq(a02);
  a01=(a01*a02);
  a00=(a00+a01);
  a01=arg[3]? arg[3][2] : 0;
  a02=arg[0]? arg[0][3] : 0;
  a03=arg[3]? arg[3][3] : 0;
  a02=(a02-a03);
  a02=casadi_sq(a02);
  a01=(a01*a02);
  a00=(a00+a01);
  a01=arg[3]? arg[3][5] : 0;
  a02=3.;
  a03=arg[3]? arg[3][8] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][4] : 0;
  a06=arg[3]? arg[3][16] : 0;
  a06=(a05-a06);
  a04=(a04*a06);
  a04=(a04*a06);
  a07=2.;
  a08=arg[3]? arg[3][9] : 0;
  a09=(a07*a08);
  a09=(a09*a06);
  a04=(a04+a09);
  a09=arg[3]? arg[3][10] : 0;
  a04=(a04+a09);
  a10=1.;
  a11=arg[3]? arg[3][25] : 0;
  a11=(a05-a11);
  a12=2.0000000000000000e-02;
  a13=(a11+a12);
  a14=1.0000000000000001e-01;
  a13=(a13/a14);
  a13=exp(a13);
  a13=(a10+a13);
  a04=(a04/a13);
  a15=(1./a13);
  a15=(a10-a15);
  a16=arg[3]? arg[3][17] : 0;
  a17=(a02*a16);
  a17=(a17*a11);
  a17=(a17*a11);
  a18=arg[3]? arg[3][18] : 0;
  a19=(a07*a18);
  a19=(a19*a11);
  a17=(a17+a19);
  a19=arg[3]? arg[3][19] : 0;
  a17=(a17+a19);
  a20=arg[3]? arg[3][34] : 0;
  a20=(a05-a20);
  a21=(a20+a12);
  a21=(a21/a14);
  a21=exp(a21);
  a21=(a10+a21);
  a17=(a17/a21);
  a22=(1./a21);
  a22=(a10-a22);
  a23=arg[3]? arg[3][26] : 0;
  a24=(a02*a23);
  a24=(a24*a20);
  a24=(a24*a20);
  a25=arg[3]? arg[3][27] : 0;
  a26=(a07*a25);
  a26=(a26*a20);
  a24=(a24+a26);
  a26=arg[3]? arg[3][28] : 0;
  a24=(a24+a26);
  a27=arg[3]? arg[3][43] : 0;
  a27=(a05-a27);
  a28=(a27+a12);
  a28=(a28/a14);
  a28=exp(a28);
  a28=(a10+a28);
  a24=(a24/a28);
  a29=(1./a28);
  a29=(a10-a29);
  a30=arg[3]? arg[3][35] : 0;
  a31=(a02*a30);
  a31=(a31*a27);
  a31=(a31*a27);
  a32=arg[3]? arg[3][36] : 0;
  a33=(a07*a32);
  a33=(a33*a27);
  a31=(a31+a33);
  a33=arg[3]? arg[3][37] : 0;
  a31=(a31+a33);
  a34=arg[3]? arg[3][52] : 0;
  a05=(a05-a34);
  a12=(a05+a12);
  a12=(a12/a14);
  a12=exp(a12);
  a12=(a10+a12);
  a31=(a31/a12);
  a14=(1./a12);
  a10=(a10-a14);
  a14=arg[3]? arg[3][44] : 0;
  a34=(a02*a14);
  a34=(a34*a05);
  a34=(a34*a05);
  a35=arg[3]? arg[3][45] : 0;
  a36=(a07*a35);
  a36=(a36*a05);
  a34=(a34+a36);
  a36=arg[3]? arg[3][46] : 0;
  a34=(a34+a36);
  a34=(a10*a34);
  a31=(a31+a34);
  a31=(a29*a31);
  a24=(a24+a31);
  a24=(a22*a24);
  a17=(a17+a24);
  a17=(a15*a17);
  a04=(a04+a17);
  a17=casadi_sq(a04);
  a24=arg[3]? arg[3][12] : 0;
  a31=(a02*a24);
  a31=(a31*a06);
  a31=(a31*a06);
  a34=arg[3]? arg[3][13] : 0;
  a37=(a07*a34);
  a37=(a37*a06);
  a31=(a31+a37);
  a37=arg[3]? arg[3][14] : 0;
  a31=(a31+a37);
  a31=(a31/a13);
  a38=arg[3]? arg[3][21] : 0;
  a39=(a02*a38);
  a39=(a39*a11);
  a39=(a39*a11);
  a40=arg[3]? arg[3][22] : 0;
  a41=(a07*a40);
  a41=(a41*a11);
  a39=(a39+a41);
  a41=arg[3]? arg[3][23] : 0;
  a39=(a39+a41);
  a39=(a39/a21);
  a42=arg[3]? arg[3][30] : 0;
  a43=(a02*a42);
  a43=(a43*a20);
  a43=(a43*a20);
  a44=arg[3]? arg[3][31] : 0;
  a45=(a07*a44);
  a45=(a45*a20);
  a43=(a43+a45);
  a45=arg[3]? arg[3][32] : 0;
  a43=(a43+a45);
  a43=(a43/a28);
  a46=arg[3]? arg[3][39] : 0;
  a47=(a02*a46);
  a47=(a47*a27);
  a47=(a47*a27);
  a48=arg[3]? arg[3][40] : 0;
  a49=(a07*a48);
  a49=(a49*a27);
  a47=(a47+a49);
  a49=arg[3]? arg[3][41] : 0;
  a47=(a47+a49);
  a47=(a47/a12);
  a50=arg[3]? arg[3][48] : 0;
  a02=(a02*a50);
  a02=(a02*a05);
  a02=(a02*a05);
  a51=arg[3]? arg[3][49] : 0;
  a07=(a07*a51);
  a07=(a07*a05);
  a02=(a02+a07);
  a07=arg[3]? arg[3][50] : 0;
  a02=(a02+a07);
  a02=(a10*a02);
  a47=(a47+a02);
  a47=(a29*a47);
  a43=(a43+a47);
  a43=(a22*a43);
  a39=(a39+a43);
  a39=(a15*a39);
  a31=(a31+a39);
  a39=casadi_sq(a31);
  a17=(a17+a39);
  a17=sqrt(a17);
  a04=(a04/a17);
  a39=arg[0]? arg[0][0] : 0;
  a03=(a03*a06);
  a03=(a03*a06);
  a03=(a03*a06);
  a08=(a08*a06);
  a08=(a08*a06);
  a03=(a03+a08);
  a09=(a09*a06);
  a03=(a03+a09);
  a09=arg[3]? arg[3][11] : 0;
  a03=(a03+a09);
  a03=(a03/a13);
  a16=(a16*a11);
  a16=(a16*a11);
  a16=(a16*a11);
  a18=(a18*a11);
  a18=(a18*a11);
  a16=(a16+a18);
  a19=(a19*a11);
  a16=(a16+a19);
  a19=arg[3]? arg[3][20] : 0;
  a16=(a16+a19);
  a16=(a16/a21);
  a23=(a23*a20);
  a23=(a23*a20);
  a23=(a23*a20);
  a25=(a25*a20);
  a25=(a25*a20);
  a23=(a23+a25);
  a26=(a26*a20);
  a23=(a23+a26);
  a26=arg[3]? arg[3][29] : 0;
  a23=(a23+a26);
  a23=(a23/a28);
  a30=(a30*a27);
  a30=(a30*a27);
  a30=(a30*a27);
  a32=(a32*a27);
  a32=(a32*a27);
  a30=(a30+a32);
  a33=(a33*a27);
  a30=(a30+a33);
  a33=arg[3]? arg[3][38] : 0;
  a30=(a30+a33);
  a30=(a30/a12);
  a14=(a14*a05);
  a14=(a14*a05);
  a14=(a14*a05);
  a35=(a35*a05);
  a35=(a35*a05);
  a14=(a14+a35);
  a36=(a36*a05);
  a14=(a14+a36);
  a36=arg[3]? arg[3][47] : 0;
  a14=(a14+a36);
  a14=(a10*a14);
  a30=(a30+a14);
  a30=(a29*a30);
  a23=(a23+a30);
  a23=(a22*a23);
  a16=(a16+a23);
  a16=(a15*a16);
  a03=(a03+a16);
  a39=(a39-a03);
  a03=(a04*a39);
  a31=(a31/a17);
  a17=arg[0]? arg[0][1] : 0;
  a24=(a24*a06);
  a24=(a24*a06);
  a24=(a24*a06);
  a34=(a34*a06);
  a34=(a34*a06);
  a24=(a24+a34);
  a37=(a37*a06);
  a24=(a24+a37);
  a37=arg[3]? arg[3][15] : 0;
  a24=(a24+a37);
  a24=(a24/a13);
  a38=(a38*a11);
  a38=(a38*a11);
  a38=(a38*a11);
  a40=(a40*a11);
  a40=(a40*a11);
  a38=(a38+a40);
  a41=(a41*a11);
  a38=(a38+a41);
  a41=arg[3]? arg[3][24] : 0;
  a38=(a38+a41);
  a38=(a38/a21);
  a42=(a42*a20);
  a42=(a42*a20);
  a42=(a42*a20);
  a44=(a44*a20);
  a44=(a44*a20);
  a42=(a42+a44);
  a45=(a45*a20);
  a42=(a42+a45);
  a45=arg[3]? arg[3][33] : 0;
  a42=(a42+a45);
  a42=(a42/a28);
  a46=(a46*a27);
  a46=(a46*a27);
  a46=(a46*a27);
  a48=(a48*a27);
  a48=(a48*a27);
  a46=(a46+a48);
  a49=(a49*a27);
  a46=(a46+a49);
  a49=arg[3]? arg[3][42] : 0;
  a46=(a46+a49);
  a46=(a46/a12);
  a50=(a50*a05);
  a50=(a50*a05);
  a50=(a50*a05);
  a51=(a51*a05);
  a51=(a51*a05);
  a50=(a50+a51);
  a07=(a07*a05);
  a50=(a50+a07);
  a07=arg[3]? arg[3][51] : 0;
  a50=(a50+a07);
  a10=(a10*a50);
  a46=(a46+a10);
  a29=(a29*a46);
  a42=(a42+a29);
  a22=(a22*a42);
  a38=(a38+a22);
  a15=(a15*a38);
  a24=(a24+a15);
  a17=(a17-a24);
  a24=(a31*a17);
  a03=(a03+a24);
  a03=casadi_sq(a03);
  a01=(a01*a03);
  a03=arg[3]? arg[3][4] : 0;
  a31=(a31*a39);
  a04=(a04*a17);
  a31=(a31-a04);
  a31=casadi_sq(a31);
  a03=(a03*a31);
  a01=(a01+a03);
  a00=(a00+a01);
  if (res[0]!=0) res[0][0]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Solver_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Solver_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
