/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1055, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};

/* Solver_cost_ext_cost_fun_jac:(i0[5],i1[2],i2[],i3[1055])->(o0,o1[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134, a135, a136, a137, a138, a139, a140, a141, a142, a143;
  casadi_real a144, a145, a146, a147, a148, a149, a150, a151, a152, a153, a154, a155;
  casadi_real a156, a157, a158, a159, a160, a161, a162;
  a000=arg[3]? arg[3][0] : 0;
  a001=arg[1]? arg[1][0] : 0;
  a002=casadi_sq(a001);
  a002=(a000*a002);
  a003=arg[3]? arg[3][1] : 0;
  a004=arg[1]? arg[1][1] : 0;
  a005=casadi_sq(a004);
  a005=(a003*a005);
  a002=(a002+a005);
  a005=arg[3]? arg[3][2] : 0;
  a006=arg[0]? arg[0][3] : 0;
  a007=arg[3]? arg[3][3] : 0;
  a006=(a006-a007);
  a007=casadi_sq(a006);
  a007=(a005*a007);
  a002=(a002+a007);
  a007=arg[3]? arg[3][5] : 0;
  a008=3.;
  a009=arg[3]? arg[3][8] : 0;
  a010=(a008*a009);
  a011=arg[0]? arg[0][4] : 0;
  a012=arg[3]? arg[3][16] : 0;
  a012=(a011-a012);
  a013=(a010*a012);
  a014=(a013*a012);
  a015=2.;
  a016=arg[3]? arg[3][9] : 0;
  a017=(a015*a016);
  a018=(a017*a012);
  a014=(a014+a018);
  a018=arg[3]? arg[3][10] : 0;
  a014=(a014+a018);
  a019=1.;
  a020=arg[3]? arg[3][25] : 0;
  a020=(a011-a020);
  a021=2.0000000000000000e-02;
  a022=(a020+a021);
  a023=1.0000000000000001e-01;
  a022=(a022/a023);
  a022=exp(a022);
  a024=(a019+a022);
  a014=(a014/a024);
  a025=(1./a024);
  a026=(a019-a025);
  a027=arg[3]? arg[3][17] : 0;
  a028=(a008*a027);
  a029=(a028*a020);
  a030=(a029*a020);
  a031=arg[3]? arg[3][18] : 0;
  a032=(a015*a031);
  a033=(a032*a020);
  a030=(a030+a033);
  a033=arg[3]? arg[3][19] : 0;
  a030=(a030+a033);
  a034=arg[3]? arg[3][34] : 0;
  a034=(a011-a034);
  a035=(a034+a021);
  a035=(a035/a023);
  a035=exp(a035);
  a036=(a019+a035);
  a030=(a030/a036);
  a037=(1./a036);
  a038=(a019-a037);
  a039=arg[3]? arg[3][26] : 0;
  a040=(a008*a039);
  a041=(a040*a034);
  a042=(a041*a034);
  a043=arg[3]? arg[3][27] : 0;
  a044=(a015*a043);
  a045=(a044*a034);
  a042=(a042+a045);
  a045=arg[3]? arg[3][28] : 0;
  a042=(a042+a045);
  a046=arg[3]? arg[3][43] : 0;
  a046=(a011-a046);
  a047=(a046+a021);
  a047=(a047/a023);
  a047=exp(a047);
  a048=(a019+a047);
  a042=(a042/a048);
  a049=(1./a048);
  a050=(a019-a049);
  a051=arg[3]? arg[3][35] : 0;
  a052=(a008*a051);
  a053=(a052*a046);
  a054=(a053*a046);
  a055=arg[3]? arg[3][36] : 0;
  a056=(a015*a055);
  a057=(a056*a046);
  a054=(a054+a057);
  a057=arg[3]? arg[3][37] : 0;
  a054=(a054+a057);
  a058=arg[3]? arg[3][52] : 0;
  a011=(a011-a058);
  a021=(a011+a021);
  a021=(a021/a023);
  a021=exp(a021);
  a023=(a019+a021);
  a054=(a054/a023);
  a058=(1./a023);
  a019=(a019-a058);
  a059=arg[3]? arg[3][44] : 0;
  a060=(a008*a059);
  a061=(a060*a011);
  a062=(a061*a011);
  a063=arg[3]? arg[3][45] : 0;
  a064=(a015*a063);
  a065=(a064*a011);
  a062=(a062+a065);
  a065=arg[3]? arg[3][46] : 0;
  a062=(a062+a065);
  a066=(a019*a062);
  a066=(a054+a066);
  a067=(a050*a066);
  a067=(a042+a067);
  a068=(a038*a067);
  a068=(a030+a068);
  a069=(a026*a068);
  a069=(a014+a069);
  a070=casadi_sq(a069);
  a071=arg[3]? arg[3][12] : 0;
  a072=(a008*a071);
  a073=(a072*a012);
  a074=(a073*a012);
  a075=arg[3]? arg[3][13] : 0;
  a076=(a015*a075);
  a077=(a076*a012);
  a074=(a074+a077);
  a077=arg[3]? arg[3][14] : 0;
  a074=(a074+a077);
  a074=(a074/a024);
  a078=arg[3]? arg[3][21] : 0;
  a079=(a008*a078);
  a080=(a079*a020);
  a081=(a080*a020);
  a082=arg[3]? arg[3][22] : 0;
  a083=(a015*a082);
  a084=(a083*a020);
  a081=(a081+a084);
  a084=arg[3]? arg[3][23] : 0;
  a081=(a081+a084);
  a081=(a081/a036);
  a085=arg[3]? arg[3][30] : 0;
  a086=(a008*a085);
  a087=(a086*a034);
  a088=(a087*a034);
  a089=arg[3]? arg[3][31] : 0;
  a090=(a015*a089);
  a091=(a090*a034);
  a088=(a088+a091);
  a091=arg[3]? arg[3][32] : 0;
  a088=(a088+a091);
  a088=(a088/a048);
  a092=arg[3]? arg[3][39] : 0;
  a093=(a008*a092);
  a094=(a093*a046);
  a095=(a094*a046);
  a096=arg[3]? arg[3][40] : 0;
  a097=(a015*a096);
  a098=(a097*a046);
  a095=(a095+a098);
  a098=arg[3]? arg[3][41] : 0;
  a095=(a095+a098);
  a095=(a095/a023);
  a099=arg[3]? arg[3][48] : 0;
  a008=(a008*a099);
  a100=(a008*a011);
  a101=(a100*a011);
  a102=arg[3]? arg[3][49] : 0;
  a015=(a015*a102);
  a103=(a015*a011);
  a101=(a101+a103);
  a103=arg[3]? arg[3][50] : 0;
  a101=(a101+a103);
  a104=(a019*a101);
  a104=(a095+a104);
  a105=(a050*a104);
  a105=(a088+a105);
  a106=(a038*a105);
  a106=(a081+a106);
  a107=(a026*a106);
  a107=(a074+a107);
  a108=casadi_sq(a107);
  a070=(a070+a108);
  a070=sqrt(a070);
  a108=(a069/a070);
  a109=arg[0]? arg[0][0] : 0;
  a110=(a009*a012);
  a111=(a110*a012);
  a112=(a111*a012);
  a113=(a016*a012);
  a114=(a113*a012);
  a112=(a112+a114);
  a114=(a018*a012);
  a112=(a112+a114);
  a114=arg[3]? arg[3][11] : 0;
  a112=(a112+a114);
  a112=(a112/a024);
  a114=(a027*a020);
  a115=(a114*a020);
  a116=(a115*a020);
  a117=(a031*a020);
  a118=(a117*a020);
  a116=(a116+a118);
  a118=(a033*a020);
  a116=(a116+a118);
  a118=arg[3]? arg[3][20] : 0;
  a116=(a116+a118);
  a116=(a116/a036);
  a118=(a039*a034);
  a119=(a118*a034);
  a120=(a119*a034);
  a121=(a043*a034);
  a122=(a121*a034);
  a120=(a120+a122);
  a122=(a045*a034);
  a120=(a120+a122);
  a122=arg[3]? arg[3][29] : 0;
  a120=(a120+a122);
  a120=(a120/a048);
  a122=(a051*a046);
  a123=(a122*a046);
  a124=(a123*a046);
  a125=(a055*a046);
  a126=(a125*a046);
  a124=(a124+a126);
  a126=(a057*a046);
  a124=(a124+a126);
  a126=arg[3]? arg[3][38] : 0;
  a124=(a124+a126);
  a124=(a124/a023);
  a126=(a059*a011);
  a127=(a126*a011);
  a128=(a127*a011);
  a129=(a063*a011);
  a130=(a129*a011);
  a128=(a128+a130);
  a130=(a065*a011);
  a128=(a128+a130);
  a130=arg[3]? arg[3][47] : 0;
  a128=(a128+a130);
  a130=(a019*a128);
  a130=(a124+a130);
  a131=(a050*a130);
  a131=(a120+a131);
  a132=(a038*a131);
  a132=(a116+a132);
  a133=(a026*a132);
  a133=(a112+a133);
  a109=(a109-a133);
  a133=(a108*a109);
  a134=(a107/a070);
  a135=arg[0]? arg[0][1] : 0;
  a136=(a071*a012);
  a137=(a136*a012);
  a138=(a137*a012);
  a139=(a075*a012);
  a140=(a139*a012);
  a138=(a138+a140);
  a140=(a077*a012);
  a138=(a138+a140);
  a140=arg[3]? arg[3][15] : 0;
  a138=(a138+a140);
  a138=(a138/a024);
  a140=(a078*a020);
  a141=(a140*a020);
  a142=(a141*a020);
  a143=(a082*a020);
  a144=(a143*a020);
  a142=(a142+a144);
  a144=(a084*a020);
  a142=(a142+a144);
  a144=arg[3]? arg[3][24] : 0;
  a142=(a142+a144);
  a142=(a142/a036);
  a144=(a085*a034);
  a145=(a144*a034);
  a146=(a145*a034);
  a147=(a089*a034);
  a148=(a147*a034);
  a146=(a146+a148);
  a148=(a091*a034);
  a146=(a146+a148);
  a148=arg[3]? arg[3][33] : 0;
  a146=(a146+a148);
  a146=(a146/a048);
  a148=(a092*a046);
  a149=(a148*a046);
  a150=(a149*a046);
  a151=(a096*a046);
  a152=(a151*a046);
  a150=(a150+a152);
  a152=(a098*a046);
  a150=(a150+a152);
  a152=arg[3]? arg[3][42] : 0;
  a150=(a150+a152);
  a150=(a150/a023);
  a152=(a099*a011);
  a153=(a152*a011);
  a154=(a153*a011);
  a155=(a102*a011);
  a156=(a155*a011);
  a154=(a154+a156);
  a156=(a103*a011);
  a154=(a154+a156);
  a156=arg[3]? arg[3][51] : 0;
  a154=(a154+a156);
  a156=(a019*a154);
  a156=(a150+a156);
  a157=(a050*a156);
  a157=(a146+a157);
  a158=(a038*a157);
  a158=(a142+a158);
  a159=(a026*a158);
  a159=(a138+a159);
  a135=(a135-a159);
  a159=(a134*a135);
  a133=(a133+a159);
  a159=casadi_sq(a133);
  a159=(a007*a159);
  a160=arg[3]? arg[3][4] : 0;
  a161=(a134*a109);
  a162=(a108*a135);
  a161=(a161-a162);
  a162=casadi_sq(a161);
  a162=(a160*a162);
  a159=(a159+a162);
  a002=(a002+a159);
  if (res[0]!=0) res[0][0]=a002;
  a001=(a001+a001);
  a001=(a001*a000);
  if (res[1]!=0) res[1][0]=a001;
  a004=(a004+a004);
  a004=(a004*a003);
  if (res[1]!=0) res[1][1]=a004;
  a161=(a161+a161);
  a161=(a161*a160);
  a160=(a134*a161);
  a133=(a133+a133);
  a133=(a133*a007);
  a007=(a108*a133);
  a160=(a160+a007);
  if (res[1]!=0) res[1][2]=a160;
  a007=(a134*a133);
  a004=(a108*a161);
  a003=(a007-a004);
  if (res[1]!=0) res[1][3]=a003;
  a003=0.;
  if (res[1]!=0) res[1][4]=a003;
  a006=(a006+a006);
  a006=(a006*a005);
  if (res[1]!=0) res[1][5]=a006;
  a004=(a004-a007);
  a007=(a026*a004);
  a006=(a038*a007);
  a005=(a050*a006);
  a003=(a019*a005);
  a103=(a103*a003);
  a155=(a155*a003);
  a103=(a103+a155);
  a155=(a011*a003);
  a102=(a102*a155);
  a103=(a103+a102);
  a153=(a153*a003);
  a103=(a103+a153);
  a152=(a152*a155);
  a103=(a103+a152);
  a155=(a011*a155);
  a099=(a099*a155);
  a103=(a103+a099);
  a099=(a005/a023);
  a098=(a098*a099);
  a151=(a151*a099);
  a098=(a098+a151);
  a151=(a046*a099);
  a096=(a096*a151);
  a098=(a098+a096);
  a149=(a149*a099);
  a098=(a098+a149);
  a148=(a148*a151);
  a098=(a098+a148);
  a151=(a046*a151);
  a092=(a092*a151);
  a098=(a098+a092);
  a103=(a103+a098);
  a098=(a006/a048);
  a091=(a091*a098);
  a147=(a147*a098);
  a091=(a091+a147);
  a147=(a034*a098);
  a089=(a089*a147);
  a091=(a091+a089);
  a145=(a145*a098);
  a091=(a091+a145);
  a144=(a144*a147);
  a091=(a091+a144);
  a147=(a034*a147);
  a085=(a085*a147);
  a091=(a091+a085);
  a103=(a103+a091);
  a091=(a007/a036);
  a084=(a084*a091);
  a143=(a143*a091);
  a084=(a084+a143);
  a143=(a020*a091);
  a082=(a082*a143);
  a084=(a084+a082);
  a141=(a141*a091);
  a084=(a084+a141);
  a140=(a140*a143);
  a084=(a084+a140);
  a143=(a020*a143);
  a078=(a078*a143);
  a084=(a084+a078);
  a103=(a103+a084);
  a084=(a004/a024);
  a077=(a077*a084);
  a139=(a139*a084);
  a077=(a077+a139);
  a139=(a012*a084);
  a075=(a075*a139);
  a077=(a077+a075);
  a137=(a137*a084);
  a077=(a077+a137);
  a136=(a136*a139);
  a077=(a077+a136);
  a139=(a012*a139);
  a071=(a071*a139);
  a077=(a077+a071);
  a103=(a103+a077);
  a077=(a026*a160);
  a071=(a038*a077);
  a139=(a050*a071);
  a136=(a019*a139);
  a065=(a065*a136);
  a129=(a129*a136);
  a065=(a065+a129);
  a129=(a011*a136);
  a063=(a063*a129);
  a065=(a065+a063);
  a127=(a127*a136);
  a065=(a065+a127);
  a126=(a126*a129);
  a065=(a065+a126);
  a129=(a011*a129);
  a059=(a059*a129);
  a065=(a065+a059);
  a103=(a103-a065);
  a065=(a139/a023);
  a057=(a057*a065);
  a125=(a125*a065);
  a057=(a057+a125);
  a125=(a046*a065);
  a055=(a055*a125);
  a057=(a057+a055);
  a123=(a123*a065);
  a057=(a057+a123);
  a122=(a122*a125);
  a057=(a057+a122);
  a125=(a046*a125);
  a051=(a051*a125);
  a057=(a057+a051);
  a103=(a103-a057);
  a057=(a071/a048);
  a045=(a045*a057);
  a121=(a121*a057);
  a045=(a045+a121);
  a121=(a034*a057);
  a043=(a043*a121);
  a045=(a045+a043);
  a119=(a119*a057);
  a045=(a045+a119);
  a118=(a118*a121);
  a045=(a045+a118);
  a121=(a034*a121);
  a039=(a039*a121);
  a045=(a045+a039);
  a103=(a103-a045);
  a045=(a077/a036);
  a033=(a033*a045);
  a117=(a117*a045);
  a033=(a033+a117);
  a117=(a020*a045);
  a031=(a031*a117);
  a033=(a033+a031);
  a115=(a115*a045);
  a033=(a033+a115);
  a114=(a114*a117);
  a033=(a033+a114);
  a117=(a020*a117);
  a027=(a027*a117);
  a033=(a033+a027);
  a103=(a103-a033);
  a033=(a160/a024);
  a018=(a018*a033);
  a113=(a113*a033);
  a018=(a018+a113);
  a113=(a012*a033);
  a016=(a016*a113);
  a018=(a018+a016);
  a111=(a111*a033);
  a018=(a018+a111);
  a110=(a110*a113);
  a018=(a018+a110);
  a113=(a012*a113);
  a009=(a009*a113);
  a018=(a018+a009);
  a103=(a103-a018);
  a018=(a109*a161);
  a009=(a135*a133);
  a018=(a018+a009);
  a009=(a018/a070);
  a107=(a107+a107);
  a134=(a134/a070);
  a134=(a134*a018);
  a108=(a108/a070);
  a109=(a109*a133);
  a135=(a135*a161);
  a109=(a109-a135);
  a108=(a108*a109);
  a134=(a134+a108);
  a108=(a070+a070);
  a134=(a134/a108);
  a107=(a107*a134);
  a009=(a009-a107);
  a107=(a026*a009);
  a108=(a038*a107);
  a135=(a050*a108);
  a161=(a019*a135);
  a015=(a015*a161);
  a100=(a100*a161);
  a015=(a015+a100);
  a161=(a011*a161);
  a008=(a008*a161);
  a015=(a015+a008);
  a103=(a103+a015);
  a015=10.;
  a058=(a058/a023);
  a154=(a154*a005);
  a101=(a101*a135);
  a154=(a154+a101);
  a154=(a058*a154);
  a150=(a150/a023);
  a150=(a150*a005);
  a154=(a154-a150);
  a095=(a095/a023);
  a095=(a095*a135);
  a154=(a154-a095);
  a154=(a021*a154);
  a154=(a015*a154);
  a103=(a103+a154);
  a135=(a135/a023);
  a097=(a097*a135);
  a094=(a094*a135);
  a097=(a097+a094);
  a135=(a046*a135);
  a093=(a093*a135);
  a097=(a097+a093);
  a103=(a103+a097);
  a049=(a049/a048);
  a156=(a156*a006);
  a104=(a104*a108);
  a156=(a156+a104);
  a156=(a049*a156);
  a146=(a146/a048);
  a146=(a146*a006);
  a156=(a156-a146);
  a088=(a088/a048);
  a088=(a088*a108);
  a156=(a156-a088);
  a156=(a047*a156);
  a156=(a015*a156);
  a103=(a103+a156);
  a108=(a108/a048);
  a090=(a090*a108);
  a087=(a087*a108);
  a090=(a090+a087);
  a108=(a034*a108);
  a086=(a086*a108);
  a090=(a090+a086);
  a103=(a103+a090);
  a037=(a037/a036);
  a157=(a157*a007);
  a105=(a105*a107);
  a157=(a157+a105);
  a157=(a037*a157);
  a142=(a142/a036);
  a142=(a142*a007);
  a157=(a157-a142);
  a081=(a081/a036);
  a081=(a081*a107);
  a157=(a157-a081);
  a157=(a035*a157);
  a157=(a015*a157);
  a103=(a103+a157);
  a107=(a107/a036);
  a083=(a083*a107);
  a080=(a080*a107);
  a083=(a083+a080);
  a107=(a020*a107);
  a079=(a079*a107);
  a083=(a083+a079);
  a103=(a103+a083);
  a025=(a025/a024);
  a158=(a158*a004);
  a106=(a106*a009);
  a158=(a158+a106);
  a158=(a025*a158);
  a138=(a138/a024);
  a138=(a138*a004);
  a158=(a158-a138);
  a074=(a074/a024);
  a074=(a074*a009);
  a158=(a158-a074);
  a158=(a022*a158);
  a158=(a015*a158);
  a103=(a103+a158);
  a009=(a009/a024);
  a076=(a076*a009);
  a073=(a073*a009);
  a076=(a076+a073);
  a009=(a012*a009);
  a072=(a072*a009);
  a076=(a076+a072);
  a103=(a103+a076);
  a109=(a109/a070);
  a069=(a069+a069);
  a069=(a069*a134);
  a109=(a109-a069);
  a026=(a026*a109);
  a038=(a038*a026);
  a050=(a050*a038);
  a019=(a019*a050);
  a064=(a064*a019);
  a061=(a061*a019);
  a064=(a064+a061);
  a011=(a011*a019);
  a060=(a060*a011);
  a064=(a064+a060);
  a103=(a103+a064);
  a124=(a124/a023);
  a124=(a124*a139);
  a128=(a128*a139);
  a062=(a062*a050);
  a128=(a128-a062);
  a058=(a058*a128);
  a124=(a124-a058);
  a054=(a054/a023);
  a054=(a054*a050);
  a124=(a124-a054);
  a021=(a021*a124);
  a021=(a015*a021);
  a103=(a103+a021);
  a050=(a050/a023);
  a056=(a056*a050);
  a053=(a053*a050);
  a056=(a056+a053);
  a046=(a046*a050);
  a052=(a052*a046);
  a056=(a056+a052);
  a103=(a103+a056);
  a120=(a120/a048);
  a120=(a120*a071);
  a130=(a130*a071);
  a066=(a066*a038);
  a130=(a130-a066);
  a049=(a049*a130);
  a120=(a120-a049);
  a042=(a042/a048);
  a042=(a042*a038);
  a120=(a120-a042);
  a047=(a047*a120);
  a047=(a015*a047);
  a103=(a103+a047);
  a038=(a038/a048);
  a044=(a044*a038);
  a041=(a041*a038);
  a044=(a044+a041);
  a034=(a034*a038);
  a040=(a040*a034);
  a044=(a044+a040);
  a103=(a103+a044);
  a116=(a116/a036);
  a116=(a116*a077);
  a131=(a131*a077);
  a067=(a067*a026);
  a131=(a131-a067);
  a037=(a037*a131);
  a116=(a116-a037);
  a030=(a030/a036);
  a030=(a030*a026);
  a116=(a116-a030);
  a035=(a035*a116);
  a035=(a015*a035);
  a103=(a103+a035);
  a026=(a026/a036);
  a032=(a032*a026);
  a029=(a029*a026);
  a032=(a032+a029);
  a020=(a020*a026);
  a028=(a028*a020);
  a032=(a032+a028);
  a103=(a103+a032);
  a112=(a112/a024);
  a112=(a112*a160);
  a132=(a132*a160);
  a068=(a068*a109);
  a132=(a132-a068);
  a025=(a025*a132);
  a112=(a112-a025);
  a014=(a014/a024);
  a014=(a014*a109);
  a112=(a112-a014);
  a022=(a022*a112);
  a015=(a015*a022);
  a103=(a103+a015);
  a109=(a109/a024);
  a017=(a017*a109);
  a013=(a013*a109);
  a017=(a017+a013);
  a012=(a012*a109);
  a010=(a010*a012);
  a017=(a017+a010);
  a103=(a103+a017);
  if (res[1]!=0) res[1][6]=a103;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Solver_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Solver_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
